# Archivo: /workspaces/Los-Animaniacs/uamishop-ventas/src/main/resources/application.yml

server:
  port: 8082
  error:
    include-message: always #importante para que se vea el mensaje de error 503
    include-binding-errors: always

spring:
  application:
    name: uamishop-ventas
  datasource:
    url: jdbc:mysql://localhost:3306/uamishop_ventas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: uamishop
    password: uamishop
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ventas
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#configuracion de cortador: define cuando debe "abrirse" el circuito(dejar de intentar llamar al servicio caido)
resilience4j:
  circuitbreaker:
    instances:
      catalogoCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10